title: Taylor Brazelton
description: My Personal Site
author: Taylor Brazelton
github: https://github.com/ryanb58
about: Software engineer by day and entrepreneur by night.
# disqus_shortname: taylorbrazelton
google_analytics: UA-XXXXXXXX-Y

permalink: /posts/:year/:month/:title/

enableTags: true
tagarray: []

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/taylorbrazelton/"
    - icon: fa-github
      link: "https://github.com/ryanb58"

# share:
#   twitter_username: github.io
#   fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/

url: "https://ryanb58.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

plugins: ["jekyll-include-cache"]
remote_theme: "mmistakes/minimal-mistakes@4.16.6"
