title: Taylor Brazelton
description: My Personal Site
author: Taylor Brazelton
github: https://github.com/ryanb58
about: I'm Programmer for Python & Django. I've made quite a few web apps, especially on Django.
# disqus_shortname: taylorbrazelton
google_analytics: UA-XXXXXXXX-Y

permalink: /posts/:year/:month/:title/

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/taylorbrazelton/"
    - icon: fa-github
      link: "https://github.com/ryanb58"

# share:
#   twitter_username: github.io
#   fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://ryanb58.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
